require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - production

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/*'
    - 'db/*/**'

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Lint/MissingSuper:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/NestedGroups:
  Max: 5
