default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_social_mine_api_development
  username: social_mine
  password: S@c1@l_m1nE
  host: localhost
  port: 5432

test:
  <<: *default
  database: e_social_mine_api_test
  username: social_mine
  password: S@c1@l_m1nE
  host: localhost
  port: 5432

production:
  url: <%= ENV["DATABASE_URL"] %>

